import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  bookSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: ROS 2 - The Robotic Nervous System',
      collapsed: false,
      items: [
        'module-1-ros2/what-is-ros2',
        'module-1-ros2/dds-architecture',
        'module-1-ros2/ros2-nodes',
        'module-1-ros2/topics-pubsub',
        'module-1-ros2/services-actions',
        'module-1-ros2/parameters-config',
        'module-1-ros2/launch-files',
        'module-1-ros2/rclpy-basics',
        'module-1-ros2/urdf-introduction',
        'module-1-ros2/humanoid-urdf',
        'module-1-ros2/rviz-visualization',
        'module-1-ros2/mini-project-joint-control',
        'module-1-ros2/summary-assessment',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin - Gazebo & Unity',
      collapsed: true,
      items: [
        'module-2-digital-twin/what-is-digital-twin',
        'module-2-digital-twin/gazebo-overview',
        'module-2-digital-twin/urdf-to-gazebo',
        'module-2-digital-twin/physics-simulation',
        'module-2-digital-twin/environment-building',
        'module-2-digital-twin/sensor-simulation',
        'module-2-digital-twin/ros2-sensor-integration',
        'module-2-digital-twin/unity-for-robotics',
        'module-2-digital-twin/unity-hdrp-rendering',
        'module-2-digital-twin/human-robot-interaction',
        'module-2-digital-twin/ros-unity-bridge',
        'module-2-digital-twin/mini-project-digital-twin',
        'module-2-digital-twin/summary-assessment',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: AI-Robot Brain - NVIDIA Isaac',
      collapsed: true,
      items: [
        'module-3-isaac/isaac-sim-overview',
        'module-3-isaac/isaac-setup',
        'module-3-isaac/importing-robots',
        'module-3-isaac/photorealistic-rendering',
        'module-3-isaac/synthetic-data-generation',
        'module-3-isaac/isaac-ros-overview',
        'module-3-isaac/isaac-ros-vslam',
        'module-3-isaac/isaac-ros-perception',
        'module-3-isaac/nav2-overview',
        'module-3-isaac/nav2-architecture',
        'module-3-isaac/isaac-ros-nav2-integration',
        'module-3-isaac/mini-project-obstacle-course',
        'module-3-isaac/summary-assessment',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action',
      collapsed: true,
      items: [
        'module-4-vla/what-is-vla',
        'module-4-vla/vla-pipeline',
        'module-4-vla/whisper-voice-commands',
        'module-4-vla/natural-language-parsing',
        'module-4-vla/llm-cognitive-planning',
        'module-4-vla/safety-guardrails',
        'module-4-vla/perception-integration',
        'module-4-vla/object-selection-manipulation',
        'module-4-vla/navigation-llm-plans',
        'module-4-vla/manipulator-control',
        'module-4-vla/vla-agent-loop',
        'module-4-vla/capstone-autonomous-humanoid',
        'module-4-vla/testing-failure-modes',
        'module-4-vla/summary-assessment',
      ],
    },
    'glossary',
  ],
};

export default sidebars;
